# .github/workflows/release.yml

name: Build, Package, and Release WPF App

on:
  # 1. 当一个 'v' 开头的标签被推送到仓库时 (例如 v1.0.0, v1.2.3)
  push:
    tags:
      - 'v*.*.*'
  # 2. 允许在 GitHub Actions 页面手动触发，并要求输入版本号
  workflow_dispatch:
    inputs:
      version:
        description: '请输入要发布的版本号 (例如: 1.2.3)'
        required: true
        type: string

jobs:
  # ===============================================================
  # Job 1: 构建 WPF 应用 (Publish)
  # ===============================================================
  build_app:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Restore, Build, and Publish
        run: |
          dotnet restore
          dotnet build --configuration Release --no-restore
          dotnet publish --configuration Release --no-build -o ./publish_output
      - name: Upload publish output
        uses: actions/upload-artifact@v4
        with:
          name: publish-output
          path: ./publish_output
          retention-days: 1

  # ===============================================================
  # Job 2: 构建安装包 (Installer Build)
  # ===============================================================
  build_installer:
    needs: build_app
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Download publish output
        uses: actions/download-artifact@v4
        with:
          name: publish-output
          path: ./publish_output
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2
      - name: Install 7-Zip
        run: choco install 7zip.install --params "'/S'"
      - name: Add 7-Zip to PATH
        run: echo "C:\Program Files\7-Zip" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        shell: pwsh
      - name: Build Installer
        shell: cmd
        run: |
          chcp 936
          7z a ./publish.7z ./publish_output/*
          move ./publish.7z ./Build/MicaSetup/Resources/Setups/publish.7z
          cd ./Build
          cmd /c build_autohpma.bat
      - name: Upload installer asset
        uses: actions/upload-artifact@v4
        with:
          name: installer-asset
          path: Build/AutoHPMA-Setup.exe
          retention-days: 1

  # ===============================================================
  # Job 3: 构建更新包 (Updater Build)
  # ===============================================================
  build_updater:
    needs: build_app
    runs-on: windows-latest
    outputs:
      version: ${{ steps.determine_version.outputs.version_number }} # 输出版本号给其他 job 使用
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Download publish output
        uses: actions/download-artifact@v4
        with:
          name: publish-output
          path: ./publish_output

      - name: Determine Version Number
        id: determine_version
        shell: bash
        run: |
          # 检查是 push 触发还是 workflow_dispatch 触发
          if [[ "${{ github.event_name }}" == "push" ]]; then
            # 从 git tag (例如 "v1.2.3") 中移除 "v"
            VERSION_NUMBER="${{ github.ref_name#v }}"
          else
            # 使用手动输入的版本号
            VERSION_NUMBER="${{ inputs.version }}"
          fi
          
          # 将版本号设置为环境变量，供后续步骤使用
          echo "APP_VERSION=${VERSION_NUMBER}" >> $GITHUB_ENV
          
          # 将版本号设置为此步骤的输出，供其他 job 使用
          echo "version_number=${VERSION_NUMBER}" >> $GITHUB_OUTPUT
          
          echo "Determined version: ${VERSION_NUMBER}"

      - name: Build Updater
        shell: cmd
        run: |
          rem 切换到中文代码页，防止 bat 脚本乱码
          chcp 936
          
          rem 复制应用文件
          xcopy /E /I /Y publish_output Update\publish
          
          rem 运行打包脚本，脚本会自动读取环境变量 %APP_VERSION%
          cd ./Update
          cmd /c "1-创建更新器.bat"
          cmd /c "2-打包新版本.bat"

      - name: Upload updater asset
        uses: actions/upload-artifact@v4
        with:
          name: updater-asset
          path: Update/AutoHPMA.Install.exe
          retention-days: 1

  # ===============================================================
  # Job 4: 创建并上传到 GitHub Release
  # ===============================================================
  create_release:
    needs: [build_installer, build_updater] # 依赖安装包和更新包
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download installer asset
        uses: actions/download-artifact@v4
        with:
          name: installer-asset
      - name: Download updater asset
        uses: actions/download-artifact@v4
        with:
          name: updater-asset
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          # 使用 build_updater job 输出的版本号来创建 tag
          tag_name: v${{ needs.build_updater.outputs.version }}
          name: Release v${{ needs.build_updater.outputs.version }}
          body: |
            New release v${{ needs.build_updater.outputs.version }}
            Auto-generated by GitHub Actions.
          files: |
            AutoHPMA-Setup.exe
            AutoHPMA.Install.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # ===============================================================
  # Job 5: 上传到 R2
  # ===============================================================
  upload_to_r2:
    needs: build_updater
    runs-on: ubuntu-latest
    steps:
      - name: Download updater asset
        uses: actions/download-artifact@v4
        with:
          name: updater-asset
      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install awscli --upgrade --user
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Upload Update Package to Cloudflare R2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.CLOUDFLARE_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.CLOUDFLARE_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: auto
        run: |
          aws s3 cp AutoHPMA.Install.exe \
            s3://${{ secrets.CLOUDFLARE_BUCKET_NAME }}/AutoHPMA.Install.exe \
            --endpoint-url https://${{ secrets.CLOUDFLARE_ACCOUNT_ID }}.r2.cloudflarestorage.com
