name: Sync Release Asset to Cloudflare R2

on:
  release:
    types: [published]

jobs:
  upload-to-r2:
    runs-on: ubuntu-latest
    steps:
      - name: Download latest release asset
        run: |
          mkdir release
          wget -O release/AutoHPMA.Install.exe \
          https://github.com/${{ github.repository }}/releases/latest/download/AutoHPMA.Install.exe

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Upload to Cloudflare R2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
        run: |
          aws --endpoint-url=https://20049c2f69ed4c795000cb90655ca4d4.r2.cloudflarestorage.com \
          s3 cp release/AutoHPMA.Install.exe s3://autohpma/AutoHPMA.Install.exe --acl public-read
