name: Upload release file to Cloudflare R2 (debug)

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: List release assets
        uses: actions/github-script@v7
        id: list-assets
        with:
          script: |
            const release = await github.rest.repos.getReleaseByTag({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag: context.payload.release.tag_name
            });
            const names = release.data.assets.map(a => a.name);
            console.log("Release assets:", names);
            return names.join(", ");

      - name: Debug - Show asset names
        run: |
          echo "Assets: ${{ steps.list-assets.outputs.result }}"

      - name: Download release asset (adjust filename after check)
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: ${{ github.repository }}
          version: ${{ github.event.release.tag_name }}
          file: AutoHPMA.Install.exe   # 这里先写你预估的文件名，打印出来后确认是否正确
          target: AutoHPMA.Install.exe
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Upload to Cloudflare R2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.CLOUDFLARE_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.CLOUDFLARE_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: auto
        run: |
          aws s3 cp AutoHPMA.Install.exe \
            s3://${{ secrets.CLOUDFLARE_BUCKET_NAME }}/AutoHPMA.Install.exe \
            --endpoint-url https://${{ secrets.CLOUDFLARE_ACCOUNT_ID }}.r2.cloudflarestorage.com
